# -*- coding: utf-8 -*-
"""GE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V6OmaQbVfWmbwwnW8cuD-PmmadzLI9Qy
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm

# ==========================================
# 1. PROBLEM DEFINITION
# ==========================================
def objective_function(x):
    """
    The cost function from the Lab Manual.
    f(X) = 500 - 20x1 - 26x2 - 4x1x2 + 4x1^2 + 3x2^2
    """
    x1, x2 = x[0], x[1]
    return 500 - 20*x1 - 26*x2 - 4*x1*x2 + 4*x1**2 + 3*x2**2

# Constraints
BOUNDS = [(-10, 10), (-10, 10)]

# ==========================================
# 2. GENETIC ALGORITHM (Real-Valued)
# ==========================================
def run_genetic_algorithm(pop_size=50, generations=50, mutation_rate=0.1):
    """
    Runs a Real-Valued Genetic Algorithm.
    Returns:
        best_solution (list): [x1, x2]
        best_cost (float): f(x_best)
        history (dict): Data for visualization {'costs': [], 'populations': []}
    """
    # Initialize Population (Real values within bounds)
    population = np.random.uniform(
        low=[b[0] for b in BOUNDS],
        high=[b[1] for b in BOUNDS],
        size=(pop_size, 2)
    )

    history = {'costs': [], 'populations': []}

    best_solution = None
    best_cost = float('inf')

    for gen in range(generations):
        # 1. Evaluate Fitness
        scores = np.array([objective_function(ind) for ind in population])

        # Track Best
        min_idx = np.argmin(scores)
        if scores[min_idx] < best_cost:
            best_cost = scores[min_idx]
            best_solution = population[min_idx].copy()

        # Store history for plots
        history['costs'].append(best_cost)
        history['populations'].append(population.copy())

        # 2. Selection (Tournament)
        new_population = []
        for _ in range(pop_size):
            # Pick 2 random parents
            candidates_idx = np.random.choice(pop_size, 2, replace=False)
            parent1, parent2 = population[candidates_idx[0]], population[candidates_idx[1]]
            score1, score2 = scores[candidates_idx[0]], scores[candidates_idx[1]]

            # Winner goes to mating pool
            winner = parent1 if score1 < score2 else parent2
            new_population.append(winner)

        parents = np.array(new_population)

        # 3. Crossover (Arithmetic Mean) & 4. Mutation (Gaussian)
        next_gen = []
        for i in range(0, pop_size, 2):
            p1 = parents[i]
            p2 = parents[i+1] if i+1 < pop_size else parents[0]

            # Crossover: Average of parents (simple real-valued crossover)
            c1 = 0.5 * (p1 + p2)
            c2 = 0.5 * (p2 + p1) # In simple averaging, children are identical, but mutation fixes this

            # Mutation: Add random noise
            if np.random.rand() < mutation_rate:
                c1 += np.random.normal(0, 1.0, 2) # Noise std dev = 1.0
            if np.random.rand() < mutation_rate:
                c2 += np.random.normal(0, 1.0, 2)

            # Clip to bounds
            c1 = np.clip(c1, [b[0] for b in BOUNDS], [b[1] for b in BOUNDS])
            c2 = np.clip(c2, [b[0] for b in BOUNDS], [b[1] for b in BOUNDS])

            next_gen.extend([c1, c2])

        population = np.array(next_gen[:pop_size])

    return best_solution, best_cost, history

# ==========================================
# 3. VISUALIZATION FUNCTIONS (Modular)
# ==========================================
def plot_solution_space(func, bounds):
    """Generates 2D Contour Map of the Solution Space."""
    x1 = np.linspace(bounds[0][0], bounds[0][1], 100)
    x2 = np.linspace(bounds[1][0], bounds[1][1], 100)
    X1, X2 = np.meshgrid(x1, x2)
    Z = func([X1, X2])

    fig, ax = plt.subplots(figsize=(8, 6))
    contour = ax.contourf(X1, X2, Z, levels=50, cmap='viridis')
    fig.colorbar(contour, label='Cost f(X)')
    ax.set_title('Solution Space: 2D Contour Map')
    ax.set_xlabel('x1')
    ax.set_ylabel('x2')
    return fig, ax

def plot_convergence(history):
    """Plots Best Cost vs Generation."""
    plt.figure(figsize=(8, 5))
    plt.plot(history['costs'], linewidth=2, color='blue')
    plt.title('Convergence History')
    plt.xlabel('Generation / Iteration')
    plt.ylabel('Best Cost Found')
    plt.grid(True)
    plt.show()

def plot_trajectory_scatter(func, bounds, history, generations_to_plot=[0, 9, 49]):
    """
    Overlay population scatter on Contour Map.
    Suitable for Population-based algos (GA, DE).
    """
    fig, ax = plot_solution_space(func, bounds) # Re-use base plot

    colors = ['red', 'cyan', 'white']
    markers = ['x', 'o', '*']

    for idx, gen_idx in enumerate(generations_to_plot):
        if gen_idx < len(history['populations']):
            pop = history['populations'][gen_idx]
            ax.scatter(pop[:, 0], pop[:, 1],
                       color=colors[idx], label=f'Gen {gen_idx+1}',
                       marker=markers[idx], edgecolors='black', alpha=0.8)

    ax.legend()
    ax.set_title(f'Solution Trajectory (Generations: {generations_to_plot})')
    plt.show()

def plot_trajectory_line(func, bounds, history):
    """
    Draws a line connecting best solutions per iteration.
    Suitable for Single-solution algos (SA, Hill Climbing).
    """
    fig, ax = plot_solution_space(func, bounds) # Re-use base plot

    # Extract best solution from each population for the line
    # (For GA, we usually track population, but we can plot the path of the 'best' individual)
    best_path = []
    for pop in history['populations']:
        costs = [func(ind) for ind in pop]
        best_path.append(pop[np.argmin(costs)])
    best_path = np.array(best_path)

    ax.plot(best_path[:, 0], best_path[:, 1], color='red', marker='o', markersize=3, linestyle='--')
    ax.scatter(best_path[-1, 0], best_path[-1, 1], color='white', marker='*', s=200, label='Final Best', zorder=5)

    ax.legend()
    ax.set_title('Solution Trajectory (Path of Best Individual)')
    plt.show()

# ==========================================
# 4. MAIN EXECUTION
# ==========================================
if __name__ == "__main__":
    # A. Run Algorithm
    print("Running Genetic Algorithm...")
    best_sol, min_cost, history_data = run_genetic_algorithm(pop_size=50, generations=50)

    # B. 4.1 Metrics Report
    print("\n" + "="*30)
    print("4.1 METRICS REPORT")
    print("="*30)
    print(f"Algorithm Used: Genetic Algorithm (Real-Valued)")
    print(f"Best Cost (fmin): {min_cost:.4f}")
    print(f"Number of Iterations: {len(history_data['costs'])}")
    print(f"Best Coordinates (x1, x2): ({best_sol[0]:.4f}, {best_sol[1]:.4f})")
    print("="*30 + "\n")

    # C. 4.2 Visualizations

    # 1. Solution Space (Just the map)
    # Note: The plotting function creates the figure but doesn't show it immediately
    # unless we call plt.show(). The functions above call plt.show() inside them.
    # To show just the blank space:
    fig, ax = plot_solution_space(objective_function, BOUNDS)
    plt.show()

    # 2. Convergence History
    plot_convergence(history_data)

    # 3. Solution Trajectory
    # Use Scatter for GA/DE (Population based)
    plot_trajectory_scatter(objective_function, BOUNDS, history_data, generations_to_plot=[0, 10, 49])

    # Uncomment below to see the 'Line' style plot (Better for SA)
    # plot_trajectory_line(objective_function, BOUNDS, history_data)